# see https://github.com/broadway/broadway-bundle

services:
  broadway.event_sourcing.aggregate_factory:
    class: Broadway\EventSourcing\AggregateFactory\PublicConstructorAggregateFactory

  Broadway\CommandHandling\CommandBus: '@broadway.command_handling.command_bus'
  Broadway\UuidGenerator\UuidGeneratorInterface: '@broadway.uuid.generator'
  Broadway\EventHandling\EventBus: '@broadway.event_handling.event_bus'
  Broadway\EventSourcing\AggregateFactory\AggregateFactory: '@broadway.event_sourcing.aggregate_factory'
