services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    expose:
      - 5672
    networks:
      - user-task
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
    environment:
      - RABBITMQ_USERNAME=dev
      - RABBITMQ_PASSWORD=dev

  elasticsearch:
    image: elasticsearch:7.10.1
    expose:
      - 9200
    networks:
      - user-task
    healthcheck:
      test: curl --output /dev/null --silent --head --fail localhost:9200
    environment:
      - discovery.type=single-node

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    networks:
      - user-task
    healthcheck:
      test: mysqladmin ping -pdev | grep "mysqld is alive"
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=user-task

  nginx:
    image: nginx:stable
    ports:
      - 80:80
    networks:
      - user-task
    volumes:
      - ./docker/nginx/sites.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    expose:
      - 9000
    networks:
      - user-task
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  command-consumer:
    build: ./docker/php-cli
    networks:
      - user-task
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    command: /app/bin/console messenger:consume command -vv

networks:
  user-task:
    driver: bridge
