version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    expose:
      - 9200
    networks:
      - user-task
    environment:
      - discovery.type=single-node

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    networks:
      - user-task
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=user-task

  nginx:
    image: nginx:stable
    ports:
      - 80:80
    networks:
      - user-task
    volumes:
      - ./docker/nginx/sites.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php-fpm
    expose:
      - 9000
    networks:
      - user-task
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - elasticsearch

networks:
  user-task:
    driver: bridge
