POST http://localhost/api/v1/users/134e3a2b-2e9f-4f7b-87d4-39fc56a35533/tasks
Accept: application/json
Content-Type: application/json

{
  "id": "6696fafd-42af-482f-a403-bc81044781c5"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}
