POST http://localhost/api/v1/tasks
Accept: application/json
Content-Type: application/json

{
  "summary": "A task to be assigned to Alice",
  "description": "This task is to be assigned to Alice"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}

###

POST http://localhost/api/v1/tasks
Accept: application/json
Content-Type: application/json

{
  "summary": "A task to be assigned to Bob",
  "description": "This task is to be assigned to Bob"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}
