POST http://localhost/api/v1/users/f7056592-acec-4ba5-aa5f-0f7c6ea32dd4/tasks
Accept: application/json
Content-Type: application/json

{
  "id": "a1555657-8575-46c4-bb17-2e7856b6bd4d"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}

###

DELETE http://localhost/api/v1/users/b1c3d328-53d3-45b3-962a-8627381181d0/tasks/6ced720c-ea96-4161-90c4-4b4be328b65c
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}
