PATCH http://localhost/api/v1/tasks/c57f1442-bc02-4f18-add7-bb30b12be297
Host: user-task.docker
Accept: application/json

{
  "status": "done"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 202");
});
%}
